### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by EnriqueBenavides** [stadtulm/cykel-lock-bl10#1]
PS D:\Git\cykel-lock-bl10> .\server.py runserver
Traceback (most recent call last):
  File "D:\Git\cykel-lock-bl10\server.py", line 15, in <module>
    ENDPOINT = os.environ['ENDPOINT']
  File "C:\Python38\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'ENDPOINT'

**Comment by robbi5** [comment]
Yep, the `server.py` needs to be configured with environment variables. I've now added a list of the required ones to the readme.
